[colorScheme]
  default = "dark"
  toggle = true

[sidebar]
  compact = false
  avatar = "/images/avatar.jpg"

[article]
  showDate = true
  showReadingTime = true

[footer]
  since = 2026
  customText = "Đức Quân · ERP/SCM Consultant"

mainSections = ["posts"]
rssFullContent = true
